CC	= cl
CFLAGS	= /O2 /W3 /MD /I..\include /I..\src /DWIN32 \
	  /D_USE_MATH_DEFINES /D_CRT_SECURE_NO_WARNINGS
LDFLAGS = /RELEASE /OUT:$(EXE)
EXE	= libxmp-tests.exe

MAIN_SOURCES	= \
 util.c \
 main.c \
 simple_module.c \
 compare_mixer_data.c \
 compare_med_synth_data.c \
 read_event_common.c \

XMP_SOURCES	= \
 ..\src\md5.c \
 ..\src\win32.c \
 ..\src\hio.c \
 ..\src\load_helpers.c \
 ..\src\loaders\itsex.c \
 ..\src\dataio.c \
 ..\src\scan.c \
 ..\src\loaders\sample.c \
 ..\src\loaders\common.c \
 ..\src\filetype.c \
 ..\src\period.c \
 ..\src\memio.c \
 ..\src\depackers\xfnmatch.c \
 ..\src\far_extras.c \
 ..\src\flow.c \
 ..\src\lfo.c \
 ..\src\rng.c \
 ..\src\path.c \

ALL_SOURCES	= $(MAIN_SOURCES) $(XMP_SOURCES)

all: $(EXE)
	$(EXE)

$(EXE): $(ALL_SOURCES) all_tests.c all_tests.rsp
	copy ..\libxmp.lib .
	copy ..\libxmp.dll .
	$(CC) /MP /nologo $(CFLAGS) $(ALL_SOURCES) @all_tests.rsp /link $(LDFLAGS) libxmp.lib

all_tests.c: all_tests.txt
	type nul > $@
	for /F "tokens=*" %%I in ( $** ) do @echo declare_test(%%I); >> $@

all_tests.rsp: all_tests.txt
	type nul > $@
	for /F "tokens=*" %%I in ( $** ) do @echo %%I.c >> $@

clean:
	del all_tests.rsp
	del libxmp.lib
	del libxmp.dll
	del *.obj
	del $(EXE)
